const blogPosts = [
    {
        id: 12,
        title: "Enhanced Blog Features: Professional Code Blocks & More",
        slug: "enhanced-blog-features",
        excerpt: "Discover the new professional features in our blog including enhanced code blocks with copy/edit functionality, table of contents, search, and improved Markdown rendering.",
        description: "Discover the new professional features in our blog including enhanced code blocks with copy/edit functionality, table of contents, search, and improved Markdown rendering.",
        date: "2025-01-20",
        tags: ["Blog", "Features", "Code Blocks", "Markdown", "UI/UX", "Web Development"],
        category: "Features",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/enhanced-blog-features.md",
        coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "12 min read"
    },
    {
        id: 1,
        title: "Mastering React Best Practices in 2025",
        slug: "react-best-practices",
        excerpt: "Explore the latest React coding practices that every frontend developer must follow in 2025.",
        description: "A complete guide to writing clean, scalable, and maintainable React applications using modern best practices, hooks, and performance tips.",
        date: "2025-01-22",
        tags: ["React", "Best Practices", "Hooks", "Frontend"],
        category: "React",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/react-best-practices.md",
        coverImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "8 min read"
    },
    {
        id: 2,
        title: "MUI Grid Mastery: Responsive Layouts Made Easy",
        slug: "mui-grid-mastery",
        excerpt: "Learn how to build responsive React layouts using MUI Grid with breakpoints, spacing, and real-world examples.",
        description: "Master Material-UI Grid system to create beautiful, responsive layouts with proper breakpoints and spacing.",
        date: "2025-01-20",
        tags: ["MUI", "Grid", "Responsive", "React"],
        category: "UI/UX",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/mui-grid-mastery.md",
        coverImage: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "6 min read"
    },
    {
        id: 3,
        title: "Firebase Firestore in 15 Minutes: Real-time Magic",
        slug: "firebase-firestore",
        excerpt: "Get up and running with Firebase Firestore, and learn how to build real-time apps in minutes.",
        description: "Master Firebase Firestore in minutes! Learn how to set up and integrate Google's powerful real-time NoSQL database.",
        date: "2025-01-18",
        tags: ["Firebase", "Firestore", "Database", "Real-time"],
        category: "Backend",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/firebase-firestore.md",
        coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "7 min read"
    },
    {
        id: 4,
        title: "Supabase vs Firebase: The Ultimate Comparison",
        slug: "supabase-vs-firebase",
        excerpt: "Discover how Supabase compares to Firebase and which one is better for your next project.",
        description: "A comprehensive comparison between Supabase and Firebase covering features, pricing, and use cases.",
        date: "2025-01-16",
        tags: ["Supabase", "Firebase", "Backend", "Comparison"],
        category: "Backend",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/supabase-vs-firebase.md",
        coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "10 min read"
    },
    {
        id: 5,
        title: "Expo APK Build Guide: Deploy Android Apps Easily",
        slug: "expo-apk-build-guide",
        excerpt: "Step-by-step guide to building Android APKs using Expo CLI with EAS Build or Classic Workflow.",
        description: "Complete guide to building and deploying Android APKs using Expo with modern EAS Build workflow.",
        date: "2025-01-14",
        tags: ["React Native", "Expo", "APK", "Deployment"],
        category: "Mobile",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/expo-apk-build-guide.md",
        coverImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "12 min read"
    },
    {
        id: 6,
        title: "Google Search Console Setup for Developers",
        slug: "google-console-setup",
        excerpt: "Set up Google Search Console like a pro, submit sitemaps, and track website performance insights efficiently.",
        description: "Complete guide to setting up Google Search Console for better SEO and website performance tracking.",
        date: "2025-01-12",
        tags: ["SEO", "Google Console", "Indexing", "Sitemap"],
        category: "SEO",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/google-console-setup.md",
        coverImage: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "9 min read"
    },
    {
        id: 7,
        title: "ChatGPT for Developers: Advanced Prompt Engineering",
        slug: "chatgpt-for-developers",
        excerpt: "Use these advanced prompt engineering tips to get better ChatGPT outputs for coding, design, and brainstorming.",
        description: "Master ChatGPT with advanced prompt engineering techniques specifically designed for developers and designers.",
        date: "2025-01-10",
        tags: ["ChatGPT", "AI", "Prompts", "Productivity"],
        category: "AI Tools",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/chatgpt-for-developers.md",
        coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "11 min read"
    },
    {
        id: 8,
        title: "React Native Performance Optimization Guide",
        slug: "react-native-performance",
        excerpt: "Learn advanced techniques to optimize your React Native app performance and user experience.",
        description: "Comprehensive guide to optimizing React Native applications for better performance and user experience.",
        date: "2025-01-08",
        tags: ["React Native", "Performance", "Optimization", "Mobile"],
        category: "Mobile",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/react-native-performance.md",
        coverImage: "https://images.unsplash.com/photo-1551650975-87deedd944c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "15 min read"
    },
    {
        id: 9,
        title: "Mobile App Deployment Checklist",
        slug: "mobile-deploy-checklist",
        excerpt: "Complete checklist for deploying mobile apps to App Store and Google Play Store successfully.",
        description: "Essential checklist covering everything you need to deploy mobile apps to both iOS and Android stores.",
        date: "2025-01-06",
        tags: ["Mobile", "Deployment", "App Store", "Google Play"],
        category: "Mobile",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/mobile-deploy-checklist.md",
        coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "8 min read"
    },
    {
        id: 10,
        title: "Web Application Deployment Checklist",
        slug: "web-deploy-checklist",
        excerpt: "Essential checklist for deploying web applications to production with best practices and security considerations.",
        description: "Complete guide to deploying web applications with security, performance, and reliability best practices.",
        date: "2025-01-04",
        tags: ["Web", "Deployment", "Production", "DevOps"],
        category: "DevOps",
        author: "Chaudhary Irfan",
        filePath: "/content/blogs/web-deploy-checklist.md",
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
        readTime: "10 min read"
    }
];

export default blogPosts;
